---
# file: ansible-gcp-servers-setup-all.yml
# configures the server instances
# This Playbook has Seven Plays

# First Play sets up critical configuration on servers
- hosts: targets
  # Ansible Facts cannot be gathered yet
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_method: sudo

  pre_tasks:
    # To operate remotely in critical files without direct user input
    - name: Remove require tty - alt
      lineinfile:
        regexp: "requiretty"
        dest: /etc/sudoers.d/os_defaults
        state: absent

    - name: Validate the sudoers file before saving not to require password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%ADMIN ALL='
        line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
    # Install the SSH key on servers
    - name: install ssh key
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
        state: present

  tasks:
    - name: apt update
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: install git
      apt:
        pkg: git
        state: present

    - name: check if directory exists
      stat:
        path: "kubernetes-starterkit/"
      register: kube_dir

    - name: remove outdated repo folder
      ansible.builtin.file:
        path: /home/ubuntu/kubernetes-starterkit
        state: absent
      when: kube_dir.stat.exists

    - name: download repo
      ansible.builtin.git:
        repo: https://github.com/Velhinho/kubernetes-starterkit.git
        dest: /home/ubuntu/kubernetes-starterkit

    - name: daemon reload
      ansible.builtin.systemd:
        daemon_reload: yes


# Second Play populates the /etc/hosts and .env
- hosts: targets
  gather_facts: True
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:
    - name: configure name resolution
      lineinfile:
        dest: /home/ubuntu/.env
        regexp: 'VUE_APP_{{ item }}=.*'
        line: "VUE_APP_{{item}}={{ hostvars[item].ansible_host }}"
        state: present
        create: yes
      when: hostvars[item].ansible_host is defined
      with_items: '{{groups.targets}}'

    - name: update /etc/hosts file for name resolution
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: '{{groups.targets}}'

    - name: check if node exporter exists
      stat:
        path: /home/ubuntu/node_exporter
      register: node_exporter_dir

    - name: install node exporter
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz
        dest: /home/ubuntu/node_exporter.tar.gz
      when: not node_exporter_dir.stat.exists

    - name: untar tar
      ansible.builtin.unarchive:
        src: /home/ubuntu/node_exporter.tar.gz
        dest: /home/ubuntu/node_exporter
        remote_src: yes
      when: not node_exporter_dir.stat.exists
          
    - name: remove service file
      ansible.builtin.file:
        path: /etc/systemd/system/start-node-exporter.service
        state: absent

    - name: copy start-node-exporter.service to systemd
      ansible.builtin.copy:
        src: /home/ubuntu/kubernetes-starterkit/infrastructure/templates/start-node-exporter.service
        dest: /etc/systemd/system/start-node-exporter.service
        remote_src: yes
   
    - name: start node exporter
      ansible.builtin.systemd:
        state: restarted
        name: start-node-exporter


#  Third Play installs npm on web servers
- hosts: web
  gather_facts: True
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:    
    - name: install npm
      apt:
        pkg: npm
        state: present


# Vue Play
- hosts: vue
  gather_facts: True
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:
    - name: copy .env to project folder
      ansible.builtin.copy:
        src: /home/ubuntu/.env
        dest: /home/ubuntu/kubernetes-starterkit/vuecalc/.env
        remote_src: yes

    - name: remove service file
      ansible.builtin.file:
        path: /etc/systemd/system/start-vue.service
        state: absent

    - name: copy start-vue.service to systemd
      ansible.builtin.copy:
        src: /home/ubuntu/kubernetes-starterkit/infrastructure/templates/start-vue.service
        dest: /etc/systemd/system/start-vue.service
        remote_src: yes
   
    - name: start vue
      ansible.builtin.systemd:
        state: restarted
        name: start-vue


# Happy Play
- hosts: happy
  gather_facts: True
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:   
    - name: copy .env to project folder
      ansible.builtin.copy:
        src: /home/ubuntu/.env
        dest: /home/ubuntu/kubernetes-starterkit/happy/.env
        remote_src: yes

    - name: remove service file
      ansible.builtin.file:
        path: /etc/systemd/system/start-happy.service
        state: absent

    - name: copy start-happy.service to systemd
      ansible.builtin.copy:
        src: /home/ubuntu/kubernetes-starterkit/infrastructure/templates/start-happy.service
        dest: /etc/systemd/system/start-happy.service
        remote_src: yes
   
    - name: start happy
      ansible.builtin.systemd:
        state: restarted
        name: start-happy
        


# Expressed Play
- hosts: expressed
  gather_facts: True
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:  
    - name: copy .env to project folder
      ansible.builtin.copy:
        src: /home/ubuntu/.env
        dest: /home/ubuntu/kubernetes-starterkit/expressed/.env
        remote_src: yes

    - name: remove service file
      ansible.builtin.file:
        path: /etc/systemd/system/start-expressed.service
        state: absent

    - name: copy start-expressed.service to systemd
      ansible.builtin.copy:
        src: /home/ubuntu/kubernetes-starterkit/infrastructure/templates/start-expressed.service
        dest: /etc/systemd/system/start-expressed.service
        remote_src: yes
   
    - name: start expressed
      ansible.builtin.systemd:
        state: restarted
        name: start-expressed


# Bootstorage Play
- hosts: bootstorage
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:
    - name: copy .env to project folder
      ansible.builtin.copy:
        src: /home/ubuntu/.env
        dest: /home/ubuntu/kubernetes-starterkit/bootstorage/.env
        remote_src: yes

    - name: install python3
      apt:
        pkg: python3
        state: present

    - name: install pip
      apt:
        pkg: python3-pip
        state: present

    - name: install python dotenv
      pip:
        name: python-dotenv
        state: present

    - name: install flask cors
      pip:
        name: flask-cors
        state: present

    - name: install flask
      apt:
        pkg: python3-flask
        state: present
          
    - name: remove service file
      ansible.builtin.file:
        path: /etc/systemd/system/start-flask.service
        state: absent

    - name: copy start-flask.service to systemd
      ansible.builtin.copy:
        src: /home/ubuntu/kubernetes-starterkit/infrastructure/templates/start-flask.service
        dest: /etc/systemd/system/start-flask.service
        remote_src: yes
   
    - name: start flask
      ansible.builtin.systemd:
        state: restarted
        name: start-flask

# Prometheus Play
- hosts: prometheus
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:
    - name: check if prometheus exists
      stat:
        path: /home/ubuntu/prometheus
      register: prometheus_dir

    - name: install prometheus
      ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.40.0-rc.0/prometheus-2.40.0-rc.0.linux-amd64.tar.gz
        dest: /home/ubuntu/prometheus.tar.gz
      when: not prometheus_dir.stat.exists

    - name: untar tar
      ansible.builtin.unarchive:
        src: /home/ubuntu/prometheus.tar.gz
        dest: /home/ubuntu/prometheus
        remote_src: yes
      when: not prometheus_dir.stat.exists
          
    - name: remove service file
      ansible.builtin.file:
        path: /etc/systemd/system/start-prometheus.service
        state: absent

    - name: copy start-prometheus.service to systemd
      ansible.builtin.copy:
        src: /home/ubuntu/kubernetes-starterkit/infrastructure/templates/start-prometheus.service
        dest: /etc/systemd/system/start-prometheus.service
        remote_src: yes
   
    - name: start prometheus
      ansible.builtin.systemd:
        state: restarted
        name: start-prometheus

