name: bootstorage restart
run-name: Restarts after every push
on: [push]

jobs:
  update-machines:
    name: Update machines
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCE_PROJECT }}
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        export_default_credentials: true

    - name: Update repo and restart bootstorage
      run: gcloud compute ssh bootstorage --zone=europe-west2-c --command="sudo bash /home/ubuntu/kubernetes-starterkit/restart.sh start-flask"
    
